---
title: "Class 13: Structure based drug discovery"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prepare HIV-protease molecule for docking 

First, get a PDB structure from the online database then clean it up for docking.

```{r}
library(bio3d)
```

```{r}
file.name <- get.pdb("1hsg")
```

```{r}
file.name
```

Read file into R and clean it up (remove non-protein bits) and also we will save the ligand into a separate file.

```{r}
hiv <- read.pdb(file.name)
hiv
```

```{r}
prot <- trim.pdb(hiv, "protein")
prot
```

```{r}
write.pdb(prot, file="1hsg_protein.pdb")
```

Do the same for the ligand:

```{r}
lig <- trim.pdb(hiv, "ligand")
lig
```

```{r}
write.pdb(lig, file="1hsg_ligand.pdb")
```

## 2.3 Inspecting your docking results
```{r}
library(bio3d)
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, "results.pdb")
```

## Normal Mode Analysis
```{r}
pdb <- read.pdb("1HEL")
m <- nma(pdb)
plot(m)
```

```{r}
mktrj(m, mode=7, file="nma_7.pdb")
```

